# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone:

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Haris # the main title

tagline: Hasanuddin University || Information System Major # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  blog,

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://Haris2512.github.io"

github:
  username: Haris2512 # change to your GitHub username

twitter:
  username: your_twitter_username # change to your Twitter username

social:
  name: Haris
  email: harissaputra1136@gmail.com
  links:
    - https://twitter.com/your_twitter_username
    - https://github.com/Haris2512
    # - https://www.facebook.com/yourusername
    # - https://www.linkedin.com/in/yourusername

# Site Verification Settings
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# or set to 'light' or 'dark'
prefer_color_scheme: 

# Reading files options
include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - yarn.lock

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

# Optional: plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Deployment Settings
# Uncomment and fill in if using GitHub Pages
# github:
#   is_project_page: false
